### ISSUE TITLE
Object(...) is not a function error in TypeScript 3.9.7 and Ionic v3(Angular v6) environments

### ISSUE THREAD

**Issue by nimuseel** [datocms/structured-text#17]
Please consider that it is a translator. 🙏

Hello, I'm Korean DatoCMS user
I'm leaving an issue because I have a question about DataCMS.

Which version of TypeScript is supported by the datocms-structured-text-to-html-string library provided by DatoCMS?

The version of TypeScript I'm using now is version 3.9.7.
The framework uses Ionic v3 (Angular v6).

The validate method of datocms-structured-text-utils was used to determine that it was a valid dast grammar. If you use the render method, the error message Object(..) is not a function is output.

Attached is a photo that proves that it is valid when validating with error message below.

![image](https://user-images.githubusercontent.com/48236404/125007988-7bb65900-e09c-11eb-884e-d6a89707716a.png)

![image](https://user-images.githubusercontent.com/48236404/125007947-68a38900-e09c-11eb-9592-cb361a38373d.png)

Please contact me if you need more information.

It works in Angular v10 & TypeScript 4.0.3 environments.
I look forward to hearing from you. Have a nice day :)

**Comment by stefanoverna** [comment]
Hi! Can you please paste here the exact structure/data that you're passing to the datocms-structured-text-to-html-string render method please? Angular/TypeScript should not be an issue here, so it must be something else.

**Comment by nimuseel** [comment]
@stefanoverna Hi, Here's the data.

```
{
    "schema": "dast",
    "document": {
        "type": "root",
        "children": [
            {
                "type": "paragraph",
                "children": [
                    {
                        "type": "span",
                        "value": "비즈넵 서비스 긴급 점검 중!"
                    }
                ]
            },
            {
                "type": "list",
                "style": "bulleted",
                "children": [
                    {
                        "type": "listItem",
                        "children": [
                            {
                                "type": "paragraph",
                                "children": [
                                    {
                                        "type": "span",
                                        "value": "작업일시: 2021.06.11 오후 2시 ~2021.06.12 오후 2시"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "listItem",
                        "children": [
                            {
                                "type": "paragraph",
                                "children": [
                                    {
                                        "type": "span",
                                        "value": "작업사항: 서비스 개선"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "type": "paragraph",
                "children": [
                    {
                        "url": "https://www.notion.so/bznav/cd055a3c2d8b40579e2867d92b2f3e75",
                        "type": "link",
                        "children": [
                            {
                                "type": "span",
                                "value": "자세한 사항 확인하기"
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
```

**Comment by stefanoverna** [comment]
Mh, I see no problems here: https://codepen.io/stefanoverna/pen/KKmMxEe

**Comment by nimuseel** [comment]
Oh... The same error occurs when stored in a separate variable. :(

```
const data: StructuredTextDocument = {
      schema: 'dast',
      document: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'span',
                value: '비즈넵 서비스 긴급 점검 중!'
              }
            ]
          },
          {
            type: 'list',
            style: 'bulleted',
            children: [
              {
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'span',
                        value: '작업일시: 2021.06.11 오후 2시 ~2021.06.12 오후 2시'
                      }
                    ]
                  }
                ]
              },
              {
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'span',
                        value: '작업사항: 서비스 개선'
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            type: 'paragraph',
            children: [
              {
                url: 'https://www.notion.so/bznav/cd055a3c2d8b40579e2867d92b2f3e75',
                type: 'link',
                children: [
                  {
                    type: 'span',
                    value: '자세한 사항 확인하기'
                  }
                ]
              }
            ]
          }
        ]
      }
    };

    const result = render(data);
    console.log(result);
    ```

**Comment by stefanoverna** [comment]
What version of datocms-structured-text-to-html-string are you using?

**Comment by nimuseel** [comment]
I am using 1.1.4 version. The same error occurs after repeated install and install several times.

**Comment by nimuseel** [comment]
@stefanoverna Are you following this issue internally? I wish I could get some help...🥲

**Comment by stefanoverna** [comment]
Are you able to share a small repository reproducing the issue? I really don't know what could be the cause honestly  🙄

**Comment by nimuseel** [comment]
I think it'll be difficult because it's a company code.. 😢  Could it be related to tsconfig?

**Comment by stefanoverna** [comment]
it does not need to be the company's code, just a small chunk of code that reproduces the issue (codepen?). my hands are kinda tied otherwise, I'm sorry

**Comment by nimuseel** [comment]
I tried to set and test the stackblitz according to our project configuration as much as possible, but it works well, and I wonder why it doesn't work well for us. That's why I talked about tsconfig. (or other deep parts)

https://stackblitz.com/edit/ionic-2dwkxk?file=pages/home/home.ts

**Comment by nimuseel** [comment]
More) I debugged it with Chrome devtool and found that child is undefined in the 42nd row of render.js. However, if you look at the node in the right toolbar 'Scope', you can see that there is a child in the node.

![image](https://user-images.githubusercontent.com/48236404/125383788-f5b74c80-e3d2-11eb-9e65-40a23b0060b7.png)

**Comment by stefanoverna** [comment]
It seems to me that children is undefined because you stopped the code execution before the ternary expression was evaluated 100%.

**Comment by nimuseel** [comment]
Oh, I understand. I'll try to figure it out more internally in this. Please don't close the issue. 🙏

**Comment by nimuseel** [comment]
@stefanoverna This issue has been resolved! The array-flatten module was installed in the project and it was solved. Thank you very much for your help. 👍 🙏
